# This example assumes you are using a default storage class
# https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#datavolume
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata: 
  name: {{ include "aziotedgevm.name" . }}-linux-dv
  labels:
  {{ include "aziotedgevm.labels" . | indent 4}}
spec:
  source:
    registry:
      url: "docker://veyalla/ubuntu-container-disk:2204-feb18_2023"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.aziotEdgeVmDiskSize }}