apiVersion: v1
kind: Secret
metadata:  
  name: {{ include "aziotedgevm.name" . }}-vm-aziotedgeconfig  
data:  
  userdata: {{ .Values.azIotEdgeConfig | b64enc }}
  {{- if .Values.rootCA }}
  rootca: {{ .Values.rootCA | b64enc }}
  {{- end }}
  {{- if .Values.deviceCACert }}
  devicecert: {{ .Values.deviceCACert | b64enc }}
  {{- end }}
  {{- if .Values.deviceCAKey }}
  devicekey: {{ .Values.deviceCAKey | b64enc }}
  {{- end }}