apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: {{ include "aziotedgevm.name" . }}-ubuntu1804
spec:
  running: true
  template:
    metadata:
      labels:
      {{ include "aziotedgevm.labels" . | indent 8}}
        kubevirt.io/domain: {{ include "aziotedgevm.name" . }}-vm
    spec:
      # nodeSelector:
      #   # TODO: Change nested to virtualization for clarity.
      #   nested: "true"
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              # This makes it exposed as /dev/vda disk attached to the VM.
              bus: virtio
            name: bootdisk
          - disk: {}              
            name: aziotedgeconfigdisk
            # set serial
            serial: D23YZ9W6WA5DJ487
          - cdrom:
              bus: sata
            name: cloudinitdisk        
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      volumes:
      - dataVolume:
         name: {{ include "aziotedgevm.name" . }}-ubuntu1804-dv
        name: bootdisk
      - name: aziotedgeconfigdisk
        secret:
          secretName: {{ include "aziotedgevm.name" . }}-vm-aziotedgeconfig
      - name: cloudinitdisk
      # https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init-userdata-as-k8s-secret
      # https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#cloudinitnocloud
        cloudInitNoCloud:
          secretRef:          
            name: sun-vm-aziotedgeconfig
