# This example assumes you are using a default storage class
# https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#datavolume
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata: 
  name: {{ include "aziotedgevm.name" . }}-ubuntu1804-dv
  labels:
  {{ include "aziotedgevm.labels" . | indent 4}}
spec:
  source:
    registry:
      # TODO: Replace this with new a container image, build from scratch.
      url: "docker://tedezed/ubuntu-container-disk:18.0"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.aziotEdgeVmDiskSize }}