# This example assumes you are using a default storage class
# https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#datavolume
# This method of creating data volume is not currently used, we use container disk (via aziot-edge-data-volume-container.yaml) with preinstalled Ubuntu 18.04 and IoT Edge binaries.
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ include "aziotedgevm.name" . }}-linux-dv
  labels:
  {{ include "aziotedgevm.labels" . | indent 4}}
spec:
  source:
    http:
      url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.aziotEdgeVmDiskSize }}