# Dockerfile to create VM container image.
FROM scratch
# Ubuntu .img images are already in qcow2 format for KVM to load.
ADD https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img /disk/