# VM's Data Volume size.
aziotEdgeVmDiskSize: 4Gi

# Flag to create K8s service/LB to allow ssh into the VM via public IP.
aziotEdgeVmEnableExternalSsh: true

# Override prefix of resource created, defaults to chart name, truncated by 40 chars.
nameOverride: aziot-edge-kubevirt

# SSH public key to access the VM.
publicSshKey: "none"

# Config file for IoT Edge runtime.
azIotEdgeConfigFile: config.toml